version: '3.8'

services:
  app:
    build:
      context: .
      target: bolt-ai-development
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
      - WRANGLER_SEND_METRICS=false
    command: pnpm run dev
