[build]
  command = "pnpm run build"
  publish = "build/client"
  functions = ".netlify/functions-internal"
  
[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_FLAGS = "--version"

[dev]
  command = "pnpm run dev"
  port = 5173
  targetPort = 5173

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    "X-Frame-Options" = "DENY"
    "X-XSS-Protection" = "1; mode=block"
    "X-Content-Type-Options" = "nosniff"
    "Referrer-Policy" = "strict-origin-when-cross-origin"

[functions]
  node_bundler = "esbuild"
  included_files = ["server/**", "public/**"]
  external_node_modules = ["@remix-run/react"] 