name: bolt-ai
region: sfo
services:
  - name: web
    image:
      registry_type: DOCR
      repository: boltiris/bolt-ai
      tag: latest
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 5173
    envs:
      - key: NODE_ENV
        value: production
      - key: WRANGLER_SEND_METRICS
        value: "false" 